const URLS = [
    {   
        id: 0,
        url : 'https://www.imdb.com/title/tt0371746/?ref_=fn_al_tt_1'
    },
    {   
        id: 1,
        url : 'https://www.imdb.com/title/tt1228705/?ref_=tt_sims_tti'
    },
    {   
        id: 2,
        url : 'https://www.imdb.com/title/tt1300854/?ref_=tt_sims_tti'
    },
    {   
        id: 3,
        url : 'https://www.imdb.com/title/tt0458339/?ref_=tt_sims_tti'
    },
    {   
        id: 4,
        url : 'https://www.imdb.com/title/tt1843866/?ref_=tt_sims_tti'
    },
    {   
        id: 5,
        url : 'https://www.imdb.com/title/tt3498820/?ref_=tt_sims_tti'
    },
    {   
        id: 6,
        url : 'https://www.imdb.com/title/tt0800369/?ref_=tt_sims_tti'
    },
    {   
        id: 7,
        url : 'https://www.imdb.com/title/tt1981115/?ref_=tt_sims_tti'
    },
    {   
        id: 8,
        url : 'https://www.imdb.com/title/tt3501632/?ref_=tt_sims_tti'
    },
    {   
        id: 9,
        url : 'https://www.imdb.com/title/tt0800080/?ref_=nv_sr_srsg_0'
    },
    {   
        id: 10,
        url : 'https://www.imdb.com/title/tt0848228/?ref_=tt_sims_tti'
    },
    {   
        id: 11,
        url : 'https://www.imdb.com/title/tt2395427/?ref_=tt_sims_tti'
    },
    {   
        id: 12,
        url : 'https://www.imdb.com/title/tt4154756/?ref_=nv_sr_srsg_0'
    },
    {   
        id: 13,
        url : 'https://www.imdb.com/title/tt4154796/?ref_=tt_sims_tti'
    },
    {   
        id: 14,
        url : 'https://www.imdb.com/title/tt0478970/?ref_=nv_sr_srsg_0'
    },
    {   
        id: 15,
        url : 'https://www.imdb.com/title/tt5095030/?ref_=tt_sims_tti'
    },
    {   
        id: 16,
        url : 'https://www.imdb.com/title/tt2250912/?ref_=nv_sr_srsg_0'
    },
    {   
        id: 17,
        url : 'https://www.imdb.com/title/tt6320628/?ref_=tt_sims_tti'
    },
    {   
        id: 18,
        url : 'https://www.imdb.com/title/tt2015381/?ref_=tt_sims_tti'
    },
    {   
        id: 19,
        url : 'https://www.imdb.com/title/tt3896198/?ref_=tt_sims_tti'
    },
    {   
        id: 20,
        url : 'https://www.imdb.com/title/tt1211837/?ref_=tt_sims_tti'
    },
    {   
        id: 21,
        url : 'https://www.imdb.com/title/tt4154664/?ref_=nv_sr_srsg_0'
    },
    {   
        id: 22,
        url : 'https://www.imdb.com/title/tt1825683/?ref_=nv_sr_srsg_0'
    }
];
module.exports = URLS ;
